sudo: false
language: c
addons:
  apt:
    packages:
      - libgmp-dev
cache:
  directories:
    - $HOME/.local/bin
    - $HOME/.stack
before_install:
  - sh tools/install-stack.sh
install:
  - stack --jobs 1 setup
  - stack --jobs 1 build --flag hakyll:-checkExternal --flag hakyll:-previewServer --flag hakyll:-watchServer --only-dependencies
script:
  - stack --jobs 1 build --flag hakyll:-checkExternal --flag hakyll:-previewServer --flag hakyll:-watchServer
  - stack sdist --pvp-bounds both
  - stack exec haskell-weekly rebuild
after_success:
  - stack tools/deploy.hs
