addons:
  apt:
    packages:
    - libgmp-dev
after_success:
- sh tools/deploy.sh
before_install:
- sh tools/install-stack.sh
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
install:
- stack setup
- stack build --only-dependencies
language: c
script:
- stack build
- stack sdist --pvp-bounds both
- stack exec haskell-weekly rebuild
sudo: false
