addons:
  apt:
    packages:
    - libgmp-dev
after_success:
- cd _hakyll/site
- echo haskellweekly.news > CNAME
- git init
- git add .
- git config --global user.email 'taylor@fausak.me'
- git config --global user.name 'Taylor Fausak'
- git commit --author 'Haskell Weekly <info@haskellweekly.news>' --message "Automatic deploy of $TRAVIS_COMMIT"
- git remote add origin "https://$GITHUB_TOKEN@github.com/haskellweekly/haskellweekly.github.io.git"
- test "$TRAVIS_BRANCH" = 'hakyll' && test "$TRAVIS_PULL_REQUEST" = 'false' && git push --force --quiet origin master
before_install:
- sh tools/install-stack.sh
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
install:
- stack setup
- stack build --only-dependencies
language: c
script:
- stack build
- stack sdist --pvp-bounds both
- stack exec haskell-weekly rebuild
sudo: false
