sudo: false
language: c
addons:
  apt:
    packages:
      - libgmp-dev
cache:
  directories:
    - $HOME/.local/bin
    - $HOME/.stack
    - .stack-work
before_install:
  - sh tools/install-stack.sh
install:
  - stack --jobs 1 setup
  - stack --jobs 1 build --only-dependencies
script:
  - stack --jobs 1 build
  - stack sdist --pvp-bounds both
  - stack exec haskell-weekly
after_success:
  - stack tools/deploy.hs
