addons:
  apt:
    packages:
    - libgmp-dev
after_success:
- cd _hakyll/site
- echo haskellweekly.news > CNAME
- git init
- git add .
- git config --global user.email 'taylor@fausak.me'
- git config --global user.name 'Taylor Fausak'
- git commit --author 'Travis CI <builds@travis-ci.org>' --message "Automatic deploy of $TRAVIS_COMMIT"
- git remote add origin "https://$GITHUB_TOKEN@github.com/haskellweekly/haskellweekly.github.io.git"
- git push --force --quiet origin master
before_install:
- mkdir -p ~/.local/bin
- export PATH="$HOME/.local/bin:$PATH"
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
cache:
  directories:
  - $HOME/.stack
install:
- stack setup
- stack build --only-dependencies
language: c
script:
- stack build
- stack exec haskell-weekly rebuild
sudo: false
