sudo: false
language: c
addons:
  apt:
    packages:
      - libgmp-dev
cache:
  directories:
    - $HOME/.local/bin
    - $HOME/.stack
before_install:
  - sh tools/install-stack.sh
install:
  - stack setup
  - stack build --only-dependencies
script:
  - stack build
  - stack sdist
  - stack exec haskell-weekly
after_success:
  - stack exec runghc tools/deploy.hs
