name: haskell-weekly
version: 0.0.0

category: Web
description: Haskell Weekly is an email newsletter
extra-source-files:
  - content/**/*
  - README.markdown
github: haskellweekly/haskellweekly.github.io
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
synopsis: An email newsletter.

executables:
  haskell-weekly:
    dependencies:
      - base
      - cmark
      - directory
      - filepath
      - text
      - time
    ghc-options:
      - -rtsopts
      - -threaded
      - -Weverything
      - -with-rtsopts=-N
      - -Wno-implicit-prelude
      - -Wno-unsafe
    main: haskell-weekly.hs
    source-dirs: executables
