name: haskell-weekly
version: '0.0.0'

category: Web
description: Haskell Weekly is a weekly Haskell newsletter.
extra-source-files: content/**/*
github: haskellweekly/haskellweekly.github.io
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: A weekly Haskell newsletter.

executables:
  haskell-weekly:
    dependencies:
      - base
      - cmark
      - directory
      - filepath
      - text
      - time
    ghc-options:
      - -rtsopts
      - -threaded
      - -Wall
      - -with-rtsopts=-N
    main: haskell-weekly.hs
    source-dirs: executables
