category: Web
description: Haskell Weekly is a weekly Haskell newsletter.
executables:
  haskell-weekly:
    dependencies:
    - base
    - hakyll
    - tagsoup
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HaskellWeekly.hs
    source-dirs: executables
extra-source-files:
- content/**/*
- README.markdown
ghc-options: -Wall
github: haskellweekly/haskellweekly.github.io
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
name: haskell-weekly
synopsis: A weekly Haskell newsletter.
version: '0.0.0'
