name: haskell-weekly
version: '0.0.0'

category: Web
description: Haskell Weekly is a weekly Haskell newsletter.
extra-source-files: content/**/*
github: haskellweekly/haskellweekly.github.io
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: A weekly Haskell newsletter.

dependencies: base
ghc-options: -Wall

library:
  dependencies:
    - hakyll
    - tagsoup
  source-dirs: library

executables:
  haskell-weekly:
    dependencies: haskell-weekly
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    main: haskell-weekly.hs
    source-dirs: executables
