name: haskell-weekly
version: 0.0.0

category: Web
description: Haskell Weekly is an email newsletter
extra-source-files: content/**/*
github: haskellweekly/haskellweekly.github.io
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: An email newsletter.

executables:
  haskell-weekly:
    dependencies:
      - base
      - cmark
      - directory
      - filepath
      - text
      - time
    ghc-options:
      - -Weverything
      - -Wno-implicit-prelude
      - -Wno-unsafe
    main: haskell-weekly.hs
    source-dirs: executables
